### ISSUE TITLE
Add a cert for www to an app that has already a cert for naked domain

### ISSUE THREAD

**Issue by cadilhac** [sjkp/letsencrypt-siteextension#30] opened 2016-02-28 21:05 UTC
For a second app, I realized that I could add the same cert for www and non-www domains. So I did it and it worked well.
I tried to come back to a first app where I had issued a cert only for the naked domain. This time I selected both www and non-www. When I hit the button to generate a cert (even in staging mode), nothing happens.

**Comment by sjkp** [comment] 2016-02-28 21:07
Thanks for the feedback - I probably need to change the code a bit, I have not tested for this scenario.

**Comment by sjkp** [comment] 2016-02-28 21:44
I just tested it - seems to work fine. Do you select both hostnames? 
![image](https://cloud.githubusercontent.com/assets/3397744/13382110/c61228f4-de6c-11e5-8fcd-c0282402b496.png)

**Comment by cadilhac** [comment] 2016-02-28 22:40
Yes I select both.

**Comment by cadilhac** [comment] 2016-02-28 23:02
Just to be sure that it was still possible to generate a cert for my app, I selected just the www, and it worked. When I select both, it doesn't.

**Comment by chadwackerman** [comment] 2016-03-02 23:05
Realize this isn't necessarily helpful but I just did exactly this and it worked fine. But see #32 for a related issue I was having. The blank page on error is definitely confusing.

**Comment by cadilhac** [comment] 2016-03-10 22:44
I confirm that nothing changed for me too, after upgrading to the latest version.

**Comment by sjkp** [comment] 2016-03-22 20:42
@cadilhac is it possible for you to try again with the updated version, 0.4.9? And report back here. Preferably with log files (you can remove your domain names if you want) https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-debug

**Comment by cadilhac** [comment] 2016-03-22 21:03
I upgraded to 0.4.9 but this time, I got a yellow screen with stack trace and exception:

The Lets Encrypt ACME server was probably unable to reach http://www.[mydomain].com/.well-known/acme-challenge/5a6fbU1Dwj-KGngvm1x93SpzkIGHkY4G8Afu-2_p7As
View error report from Lets Encrypt at https://acme-staging.api.letsencrypt.org/[...]/MDpeykPoc2Biy9FfeS8z3gG2LqBDKofdeNpFKZmMtF4 for more information

I don't believe that it's not able to reach this particular folder, because my app didn't change since last time and if I type the url in the address bar manually, I can get the response.

**Comment by chadwackerman** [comment] 2016-03-22 21:26
See #36 the solution is walking amongst us

**Comment by sjkp** [comment] 2016-03-23 10:08
@cadilhac sorry for using you as a tester for this, but I haven't been able to reproduce the error. I have implemented @chadwackerman fix - but I don't feel confident that this is the perfect fix, if the problem really is that azure doesn't response in a timely manner, because Lets encrypts servers could hit another node than the one the code is hitting if you are running multiple instances or the 10 seconds could simply be too little.

**Comment by cadilhac** [comment] 2016-03-23 12:49
I tried with 0.4.11 and it worked !! (staging, I didn't try in real mode).
I also noted that it took 35s for the page to reload in case this can help you decode what timeouts are involved...

**Comment by sjkp** [comment] 2016-03-24 15:23
@cadilhac great - thank you so much for the help. It does take a while, even when no timeouts are involved. 35s sounds reasonable. 
I'm closing the issue, but just ping me if you experience any other problems.

**Closed by sjkp** 2016-03-24 15:23 UTC
Labels: bug
