### ISSUE TITLE
Error 400 bad request - Requested tenant identifier

### ISSUE THREAD

**Issue by misterjaytee** [sjkp/letsencrypt-siteextension#108] opened 2017-02-22 07:12 UTC
Hi,

I've used this extension for about 10 webapps now and all okay.

However the latest installation on an app service is giving me this error when clicking Next after the first page (first page shows all of the letsencrypt application settings correctly):

> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90002: Requested tenant identifier '< tenant id >' is not valid. Trace ID: < guid > Correlation ID: < guid > Timestamp: 2017-02-21 21:23:02Z ---> System.Net.WebException: The remote server returned an error: (400) Bad Request. at System.Net.HttpWebRequest.GetResponse() at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task) at LetsEncrypt.SiteExtension.ArmHelper.GetWebSiteManagementClient(IAuthSettings model) in J:\Projects\letsencrypt-siteextension\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 18 at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model) ErrorCode: invalid_request StatusCode: 400 

This is for the root app service which also has deployment slots - I'm not trying to deploy this to the slots at the moment.

I don't have authentication switched on and this is an empty web app at the moment so no special routing has been setup.

Any ideas - is this possibly a bug? And is there anything I can do to help debug the issue?

Rgds,

Jim

**Comment by sjkp** [comment] 2017-02-22 08:48
I'm not able to reproduce this. Which region are you deploying in. Are you using the guid or the domain name (myemailhotmail.onmicrosoft.com) in the tenant box? 

Sounds like something is wrong with your tenant information but when I test with a wrong tenant id I get a different error message like 
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90002: No service namespace named 'f386b536-faf3-4000-adec-2f6d78dbf0bf' was found in the data store. Trace ID: a486aecb-3647-483e-9fa8-f672f712e13d Correlation ID: eff90a67-fbaf-4e96-9722-49efff842167 Timestamp: 2017-02-22 08:46:01Z

Are you running the latest version?

**Comment by misterjaytee** [comment] 2017-02-22 10:58
Hi,

Using the domain (same domain/tenant id that I've used on other web apps) - format of tenant id is user@domain.onmicrosoft.com. And as I was writing that, I realised I'd messed up! Corrected tenant id to domain.onmicrosoft.com.

I made this mistake as I was writing some powershell script to set the app settings and trying to pick up the various parts required (rather than copy and paste the 7 settings required into Application Settings each time I do one of these) - unfortunately I picked up the account id instead of the domain and didn't spot this. Sorry for wasting your time, although probably worth leaving this here in case someone else gets a similar issue.

P.S. using new version v0.5.9 and this works fine.

Thanks.

Jim

**Comment by sjkp** [comment] 2017-02-22 20:12
@misterjaytee thanks for letting me know. I will close the issue, it is still here for future reference.

**Closed by sjkp** 2017-02-22 20:12 UTC

**Comment by twkiba** [comment] 2018-12-21 11:51
hi @sjkp I've just run into this issue as well, difference being I'm trying to use this in Azure China.  The tenant ID i'm using is of the format user@domain.partner.onmschina.cn, and I got this error:

`Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90002: Requested tenant identifier '{EmailHidden}' is not valid and not valid external domain format `

I installed the plugin from Extensions in Web Apps so should be the latest version from there.  Could be I'm missing something easy here, any idea ?

Thanks

**Comment by twkiba** [comment] 2018-12-24 08:48
I also tried using the directory ID and saw an error message as well

**Comment by twkiba** [comment] 2018-12-24 09:09
Updating with full error message:

`Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90002: Tenant myazuretenant.onmschina.cn not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator. Timestamp: 2018-12-24 09:07:22Z ---> System.Net.WebException: The remote server returned an error: (400) Bad Request. at System.Net.HttpWebRequest.GetResponse() at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, ClientCredential clientCredential) at LetsEncrypt.Azure.Core.ArmHelper.GetToken(IAzureEnvironment model) in D:\a\1\s\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 41 at LetsEncrypt.Azure.Core.ArmHelper.GetWebSiteManagementClient(IAzureWebAppEnvironment model) in D:\a\1\s\LetsEncrypt.SiteExtension.Core\ArmHelper.cs:line 19 at LetsEncrypt.SiteExtension.Controllers.HomeController.Index(AuthenticationModel model) in D:\a\1\s\LetsEncrypt-SiteExtension\Controllers\HomeController.cs:line 40 ErrorCode: invalid_request StatusCode: 400`

**Comment by twkiba** [comment] 2018-12-25 10:45
hi @sjkp thanks for the link, that gives me a new direction to try.  i'll look into and see how it works
