### ISSUE TITLE
unable to get it to work with deployment slot

### ISSUE THREAD

**Issue by kogalino** [sjkp/letsencrypt-siteextension#120] opened 2017-04-05 11:51 UTC
Hi,

I am trying to get the extension working with a deployment slot of my app service in azure.
The extension works fine with the primary (production) slot of that web app. Now I am trying to get it work with a deployment slot.

I installed the extension (v0.6.14) in the deployment slot's scm-page. I copied the environment variables from the primary slot to the deployment slot: letsencrypt:* + AzureWebJobsDashboard and AzureWebJobsStorage.
I open the extension, enter the deployment slot name and see the domains associated with it on the next page.
When I try to request a cert (staging enabled), I get an error that letsencrypt was not able to access the /.well-known/... path. The path is accessable, I manually created the folder .well-known/acme-challenge and put a file in there and I am able to request it with the browser.

The path .well-known/acme-challenge in the deployment slot's application is not created by the extension. I believe this is the issue to look at.

Is there a way to find out why the extension does not create the folder?

I did not change anything with the Service Principal. Do I need to?

Best regards and I appreciate any help to figure this out.

**Comment by sjkp** [comment] 2017-04-05 14:14
When the path is not created in the slot it is most likely a regression error due to me changing how the files are placed there. The old version just used the local file system and new version uses the KUDU API. I will test that scenario, and get back to you (unfortunately, I have yet to create automatic test cases, which is why these errors happens :( ).

**Comment by sjkp** [comment] 2017-04-05 14:18
Yes just checked my kudu client relies on the appsetting APPSETTING_WEBSITE_SITE_NAME  which is not named after the slot but after the production site. So need to make a workaround for it to work with slots.

**Comment by kogalino** [comment] 2017-04-05 14:32
Hi, thanks. I am looking forward when this issue gets resolved.

**Comment by sjkp** [comment] 2017-04-05 22:29
Should be fixed now.

**Closed by sjkp** 2017-04-05 22:29 UTC
Labels: bug

**Comment by kogalino** [comment] 2017-04-06 07:47
Thank you very much. It works perfectly.
