### ISSUE TITLE
502 - Web server received an invalid response while acting as a gateway or proxy server.

### ISSUE THREAD

**Issue by modemgeek** [sjkp/letsencrypt-siteextension#331] opened 2019-10-02 16:15 UTC
On one particular webapp, we started getting this 502 error when going to the /letsencrypt/
We haven't made any changes to it.  I have also tried upgrade to 0.9.6 (from 0.9.5) but same issue happens.  Once you are on /letsencrypt and click Next it hangs for a bit and then the 502 error pops up.  Any idea of what is causing this behavior or where I can look for errors?

I can also browse to /letsencrypt/Home/Install and select a hostname.  When I click the button request and install certificate, I get the same 502 error.

**Comment by modemgeek** [comment] 2019-10-02 17:14
**Update:  it looks like it is happening to our webapps in the south region only

**Comment by ncote** [comment] 2019-10-02 23:51
Same here.  Just noticed it a few minutes ago.

**Comment by tdoumas** [comment] 2019-10-03 11:43
We have the same problem here. North Europe.
Maybe something changed in Let's Encrypt API.
I have found a related question in ServerFault https://serverfault.com/questions/986517/error-creating-letsencrypt-certificate-from-azure-web-site-extension

No solution for the moment

**Comment by sjkp** [comment] 2019-10-03 16:02
Hi guys - i will take a look tonight.

**Comment by modemgeek** [comment] 2019-10-03 16:05
Thanks.  I also wonder if it has anything to do with LE current status

October 3, 2019 01:57 UTC[Investigating] We are investigating user reports for occasional timeouts when accessing the /directory endpoint.

**Comment by ak23young** [comment] 2019-10-03 21:05
Hey all, just wanted to add in I'm also receiving the 502 error on my webapp hosted in Central US

**Comment by sjkp** [comment] 2019-10-03 21:20
Quick update -  I won't be able to release a fix tonight. I moving to a new ACME library that supports the LetsEncrypt V2 API - which is kinda requires as the old V1 api is being shutdown first of 1. november and the staging environment is already closed (which could be why you see the errors, the extension at least wont work at all right now with staging certs). I will hopefully be able to release it tomorrow, I just have to do some more testing.

**Comment by ncote** [comment] 2019-10-03 21:23
Thank you so much.

**Comment by imadsani** [comment] 2019-10-07 11:45
Glad we're not the only ones experiencing this issue, had me worried for a minute.

Region: East Asia

**Comment by VicSmith** [comment] 2019-10-07 17:16
Noting the same problem today in the Central US Azure Region.

**Comment by tiltsoftware** [comment] 2019-10-07 18:13
Just following up to see if this is close to being resolved?

Thanks so much for your work with this, saved me a lot of time over the last few years.

**Comment by sjkp** [comment] 2019-10-07 21:43
You should move to version 1.0.1 then should should be able to renew your certs. If you have any issues please report them.

**Comment by VexedSyd** [comment] 2019-10-07 23:35
Good day,
I have updated the extension to latest version (clean install) and I am still getting the 502 error.
I am not sure if this issue is related to v2 API because I am getting the error before requesting the certificate on the _Authentication Settings_ page, as soon as I click on the _Next_ button.

**Comment by modemgeek** [comment] 2019-10-07 23:39
Same here.  Upgraded to 1.0.1.  Did a restart.  Still getting the 502 error

**Comment by VicSmith** [comment] 2019-10-07 23:54
Same here. Brand new fresh install of App, then extension.  Still getting the same 502 error.

**Comment by tiltsoftware** [comment] 2019-10-08 00:37
I'm still also seeing the same behavior with 1.0.1 with the 502 error. Thanks for working on this.

I have about 50 domains on a site so in the meantime I am using this tool to manually create the certificates. Much faster than any other manual process I have found so far and it has bought me a few days. Just in case it helps someone else. [](https://zerossl.com/free-ssl/)

**Comment by shane-hall** [comment] 2019-10-08 02:11
I'm getting the same error in Australia South-East. I tried updating the plug-in as well as removing and replacing. I see an error in the Web Job console that might be related;

> The configuration is not properly set for the Microsoft Azure WebJobs Dashboard.
> In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.
> 
> Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.

**Comment by bclevering** [comment] 2019-10-08 07:51
The same problem here... The POST to /letsencrypt is failing with a HTTP 502 Bad Gateway response on all websites hosted in West Europe. (i don't have any other)

**Comment by fredrik-annytab** [comment] 2019-10-08 07:59
I have the same problem with version 1.0.1. I can click play on the extension but when I try to click on next it takes some minutes and fails with "502 - Web server received an invalid response while acting as a gateway or proxy server."

North Europe

**Comment by rutgervanwilligen** [comment] 2019-10-08 08:02
Got the same issue today, but it might be unrelated to the Site Extension version. Yesterday, I successfully renewed a certificate using version 0.9.6. Today, in a different app service, I got a 502 using version 0.9.6 and after upgrading to 1.0.1.

**Comment by DanielHosseini** [comment] 2019-10-08 08:10
@sjkp, I'm also facing the same issue with 1.0.1. Performing the post to /letsencrypt gives a 502 bad gateway error. Any update?

**Comment by sjkp** [comment] 2019-10-08 09:36
Does anyone have a site that they don't mind me getting access to, so I can see this bad gateway error (because it doesn't happen on my sites, so I'm guessing MS is rolling out a patch to their scale units that breaks stuff, but I need to be on one of the updated scale units to reproduce it). You can write me on mail@sjkp.dk

**Comment by paul-villagesoftware** [comment] 2019-10-08 10:03
> Does anyone have a site that they don't mind me getting access to, so I can see this bad gateway error (because it doesn't happen on my sites, so I'm guessing MS is rolling out a patch to their scale units that breaks stuff, but I need to be on one of the updated scale units to reproduce it). You can write me on [mail@sjkp.dk](mailto:mail@sjkp.dk)

Happy to help, we have a site showing the symptoms. I've sent you an email.

**Comment by Jjarrard** [comment] 2019-10-08 12:07
Brilliant extension, and has saved me time and money over the years, just wanted to mention I had the same 502 bad gateway, Central US. Thanks for your hard work!

**Comment by sjkp** [comment] 2019-10-08 12:48
If you have the settings stored in app settings already you can skip the first next button, by just going to
`letsencrypt/home/install` 
If you dont have the app settings setup, then you need to do that without the help from the extension, until I figure out what is prevent it from allowing next to be clicked on the first page.

**Comment by stevet26** [comment] 2019-10-08 13:05
Thanks for looking into it and posting a work around. I have added the app setting manually and I can now see the Request and Install Certificate page with my domain in the hostname box.

Sadly, I hit the 502 error again when clicking the "Request and Install Certificate" button. 

Let me know if there is anything I can send you to help with this...

**Comment by m4nthys** [comment] 2019-10-08 15:23
> If you have the settings stored in app settings already you can skip the first next button, by just going to
> `letsencrypt/home/install`
> If you dont have the app settings setup, then you need to do that without the help from the extension, until I figure out what is prevent it from allowing next to be clicked on the first page.

Hi, could you please send the name of the attributes so I can add it manually in settings?

Thanks a lot!
Diego

**Comment by modemgeek** [comment] 2019-10-08 16:09
> @modemgeek i call that BS, because - i tested a fresh web app created friday it worked fine with my updates when I did the final testing yesterday. Then I create a new web app today, after the new bug reports and the exact same extension code on a new web app with the exact same settings, and it fails with this 502 error. I can see that it does throw an internal 500 from the IIS site, when I enable failed request tracing, but there are no error details in that error, and I'm assuming that the 502 is because of timeout between the load balancers that sit in front of Web Apps and the kudu iis process after it failed.
> Even better the same error can be reproduced by going to a web job in the kudu portal and attempting to replay an old execution. That also causes a POST request to the kudu site, which run forever and eventually returns a 502.

I don't disagree with you.  Trying to convince Microsoft it's an issue on their end or something they caused is extremely difficult.  I've been on this path with them many times.

**Comment by bistok** [comment] 2019-10-08 16:33
I’m getting this on normal azure sites that don’t use the extension but have heavy load the users are reporting getting the 502 using the site .

On Oct 8, 2019, at 10:58 AM, Simon J.K. Pedersen <notifications@github.com> wrote:

﻿

@modemgeek<https://github.com/modemgeek> i call that BS, because - i tested a fresh web app created friday it worked fine with my updates when I did the final testing yesterday. Then I create a new web app today, after the new bug reports and the exact same extension code on a new web app with the exact same settings, and it fails with this 502 error. I can see that it does throw an internal 500 from the IIS site, when I enable failed request tracing, but there are no error details in that error, and I'm assuming that the 502 is because of timeout between the load balancers that sit in front of Web Apps and the kudu iis process after it failed.

Even better the same error can be reproduced by going to a web job in the kudu portal and attempting to replay an old execution. That also causes a POST request to the kudu site, which run forever and eventually returns a 502.

**Comment by tuin007** [comment] 2019-10-08 17:35
Any news about this error?
I still get this error when trying to add a domain in let encrypt

**Comment by sjkp** [comment] 2019-10-08 21:35
Nothing yet - and I cant fix it myself, I hope Microsoft will return with an answer.

**Comment by shanselman** [comment] 2019-10-08 23:08
@sjkp what's up? We are rolling out 3.0 all over and it should be done this week I think. Your extension requires it? (I care because I have 19 sites using it) http://aspnetcoreon.azurewebsites.net/

We appreciate you @sjkp

**Comment by modemgeek** [comment] 2019-10-08 23:12
> @sjkp what's up? We are rolling out 3.0 all over and it should be done this week I think. Your extension requires it? (I care because I have 19 sites using it) http://aspnetcoreon.azurewebsites.net/
> We appreciate you @sjkp
> I'll ask someone on the App Service team.

Scott, what are the chances Microsoft will include a built in service that lets us use free LE certificates?

**Comment by shanselman** [comment] 2019-10-09 02:11
@modemgeek I'll let you know ASAP as that happens.

For now I have engaged engineers on the App Service team and I'll report back soon!

**Comment by DylanTusler** [comment] 2019-10-09 03:55
Hey ho, just chiming in to say I also am having this issue with 1.0.1 in Australia South East. This is, by the way, an amazing little tool. Thanks for keeping it running as long as you have.

**Comment by DylanTusler** [comment] 2019-10-09 04:21
I've managed to get it working in my instance by reinstating the webjobs connection strings. For some reason they are not present in my sites.

Do this by selecting an appropriate storage account in Azure portal to use for the webjob (Select "Storage Accounts" from menu bar then choose a storage account in the appropriate subscription/location), then navigate to the "Access Keys" blade, and copy one of the connection strings onto the clipboard.

Now return to the App Service (or website) that you are trying to re-establish SSL for ("App Services" on the left menu, then select an app.) Once there, open the Configuration blade under Settings and add two new connection strings, one called AzureWebJobsDashboard and one called AzureWebJobsStorage. I used the same connection string for both.

Now you can go to the Webjobs blade (also under Settings) and restart the webjob.

That fixed it for me.

**Comment by milan-stojanovic** [comment] 2019-10-09 11:14
> I've managed to get my webjobs working in my instance by reinstating the webjobs connection strings. For some reason they are not present in my sites. THIS DOES NOT FIX THE TOOL UI but will fix situations where your certificates are not renewing because the webjob has stopped working.
> 
> Do this by selecting an appropriate storage account in Azure portal to use for the webjob (Select "Storage Accounts" from menu bar then choose a storage account in the appropriate subscription/location), then navigate to the "Access Keys" blade, and copy one of the connection strings onto the clipboard.
> 
> Now return to the App Service (or website) that you are trying to re-establish SSL for ("App Services" on the left menu, then select an app.) Once there, open the Configuration blade under Settings and add two new connection strings, one called AzureWebJobsDashboard and one called AzureWebJobsStorage. I used the same connection string for both.
> 
> Now you can go to the Webjobs blade (also under Settings) and restart the webjob.
> 
> That fixed it for me.

Yep, that fixed it for me. Thanks! WebJob now works properly.

**Comment by Samelandslaget** [comment] 2019-10-09 12:54
> 
> 
> I've managed to get my webjobs working in my instance by reinstating the webjobs connection strings. For some reason they are not present in my sites. THIS DOES NOT FIX THE TOOL UI but will fix situations where your certificates are not renewing because the webjob has stopped working.
> 
> Do this by selecting an appropriate storage account in Azure portal to use for the webjob (Select "Storage Accounts" from menu bar then choose a storage account in the appropriate subscription/location), then navigate to the "Access Keys" blade, and copy one of the connection strings onto the clipboard.
> 
> Now return to the App Service (or website) that you are trying to re-establish SSL for ("App Services" on the left menu, then select an app.) Once there, open the Configuration blade under Settings and add two new connection strings, one called AzureWebJobsDashboard and one called AzureWebJobsStorage. I used the same connection string for both.
> 
> Now you can go to the Webjobs blade (also under Settings) and restart the webjob.
> 
> That fixed it for me.

This worked for me too. Adding the connection string settings and restarting (actually stopping and starting because there was no Restart button) the web job resulted in the certificate for my site being renewed immediately. (It would've expired in 4 days.) Thank you so much!

**Comment by fredrik-annytab** [comment] 2019-10-09 13:11
I decided to test another Let's encrypt implementation (App Service Acmebot) and it worked. Found it from https://letsencrypt.org/docs/client-options/ and wrote a blog post about the implementation: https://www.annytab.com/setup-lets-encrypt-for-azure-web-apps/

I really hope that this extension starts to work, but the implementation above is an alternative.

**Comment by EricHerlitz** [comment] 2019-10-09 13:14
> This worked for me too. Adding the connection string settings and restarting (actually stopping and starting because there was no Restart button) the web job resulted in the certificate for my site being renewed immediately. (It would've expired in 4 days.) Thank you so much!

While this may work to renew certificates creating new ones still doesn't work.

I'd also like to know (and this should be specified in the documentation) if the ConnectionStrings are set as appsettings or as connectionstrings.

**Comment by modemgeek** [comment] 2019-10-09 15:24
> I decided to test another Let's encrypt implementation (App Service Acmebot) and it worked. Found it from https://letsencrypt.org/docs/client-options/ and wrote a blog post about the implementation: https://www.annytab.com/setup-lets-encrypt-for-azure-web-apps/
> 
> I really hope that this extension starts to work, but the implementation above is an alternative.

i'm testing this out as well.  However, the challenge file gets placed in /site/.well-known folder.  The webapp extension places it in /site/wwwroot/.well-known.  The problem I have is that the former is not a accessible via HTTP.  I also noticed that it created another virtual directory called /.well-known which maps to /site/.well-known and it causes a run time error.

**Comment by Petryxasport** [comment] 2019-10-09 15:31
I still have the same issue with .Net V4.7 and with extension: Azure Let's Encrypt (No Web Jobs) v. 1.0.1 as well

**Comment by sjkp** [comment] 2019-10-09 15:36
@EricHerlitz you can infact install certificates on a new site too. You dont have to use the UI to setup the app settings, you can add them all manually and then just run the web job as you describe. 

The app settings you would need to add are the following: 

| Key |	Value
|-----| ----
| letsencrypt:Tenant |	The tenant name e.g. myazuretenant.onmicrosoft.com
| letsencrypt:SubscriptionId |	The subscription id
| letsencrypt:ClientId	| The value of the clientid of the service principal
| letsencrypt:ClientSecret	| The secret for the service principal
| letsencrypt:ResourceGroupName |	The name of the resource group this web app belongs to
| letsencrypt:ServicePlanResourceGroupName |	The name of the resource group with the app service plan that hosts the web app, if the app service plan is in the same plan as the web app, then this property is optional. 
| letsencrypt:AcmeBaseUri |	The url to Let's Encrypt servers e.g. https://acme-v02.api.letsencrypt.org/directory or https://acme-staging-v02.api.letsencrypt.org/directory (defaults to this)
| letsencrypt:Email	| The Email used for registering with Let's Encrypt
| letsencrypt:Hostnames |	Comma separated list of custom hostnames (externally hosted setup with CNames), that should automatically be configured for the site.

**Comment by EricHerlitz** [comment] 2019-10-09 16:51
> @EricHerlitz you can infact install certificates on a new site too. You dont have to use the UI to setup the app settings, you can add them all manually and then just run the web job as you describe.

That I know, and I have those setup already but the web jobs still returns a 502 even if I go directly to /letsencrypt/home/install in kudo

**Comment by joshdickerson92** [comment] 2019-10-09 16:52
Firstly, thanks @sjkp this really is a great extension! 

I'm having the same issue as above when creating a new certificate and tried the above, however my web job is stuck in "Pending Restart" with the error below:

Any ideas anyone? Thanks in advance!

```
The configuration is not properly set for the Microsoft Azure WebJobs Dashboard. A connection string named AzureWebJobsDashboard is not well-formed.
In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.

Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.
```

**Comment by stephanjohnson** [comment] 2019-10-09 18:43
> If you have the settings stored in app settings already you can skip the first next button, by just going to
> `letsencrypt/home/install`
> If you dont have the app settings setup, then you need to do that without the help from the extension, until I figure out what is prevent it from allowing next to be clicked on the first page.

This worked for me.

**Comment by CarlosAndreuLlaneras** [comment] 2019-10-09 21:07
> I decided to test another Let's encrypt implementation (App Service Acmebot) and it worked. Found it from https://letsencrypt.org/docs/client-options/ and wrote a blog post about the implementation: https://www.annytab.com/setup-lets-encrypt-for-azure-web-apps/
> 
> I really hope that this extension starts to work, but the implementation above is an alternative.

Thanks @fredrik-annytab, it worked for me. 
Fortunately, right now my web is ssl secured again.
Anyway, I will be watching this issue in order to use Azure Let's Ecript Extension again.

**Comment by RobDeVoer** [comment] 2019-10-09 21:48
> > This worked for me too. Adding the connection string settings and restarting (actually stopping and starting because there was no Restart button) the web job resulted in the certificate for my site being renewed immediately. (It would've expired in 4 days.) Thank you so much!
> 
> While this may work to renew certificates creating new ones still doesn't work.
> 
> I'd also like to know (and this should be specified in the documentation) if the ConnectionStrings are set as appsettings or as connectionstrings.

Set them as connection strings with type other

**Comment by m4nthys** [comment] 2019-10-10 01:30
> @EricHerlitz you can infact install certificates on a new site too. You dont have to use the UI to setup the app settings, you can add them all manually and then just run the web job as you describe.
> 
> The app settings you would need to add are the following:
> 
> Key	Value
> letsencrypt:Tenant	The tenant name e.g. myazuretenant.onmicrosoft.com
> letsencrypt:SubscriptionId	The subscription id
> letsencrypt:ClientId	The value of the clientid of the service principal
> letsencrypt:ClientSecret	The secret for the service principal
> letsencrypt:ResourceGroupName	The name of the resource group this web app belongs to
> letsencrypt:ServicePlanResourceGroupName	The name of the resource group with the app service plan that hosts the web app, if the app service plan is in the same plan as the web app, then this property is optional.
> letsencrypt:AcmeBaseUri	The url to Let's Encrypt servers e.g. https://acme-v02.api.letsencrypt.org/directory or https://acme-staging-v02.api.letsencrypt.org/directory (defaults to this)
> letsencrypt:Email	The Email used for registering with Let's Encrypt
> letsencrypt:Hostnames	Comma separated list of custom hostnames (externally hosted setup with CNames), that should automatically be configured for the site.

I've added all the app settings manually and got the same error after clicking "Request and install certificate" in the following URL: https://icollectprod.scm.azurewebsites.net/letsencrypt/home/install

=/

**Comment by RobDeVoer** [comment] 2019-10-10 02:09
My sites have been out all day due to somehow the certificates generated through the webjobs not being valid? Looked and tried for a long time to resolve this but unable to.
Bought a few certificates to get my clients back online. Hoping for a solution to the 502 error before I have more sites needing a certificate.

@shanselman any feedback from the service team?

**Comment by DylanTusler** [comment] 2019-10-10 03:49
> > This worked for me too. Adding the connection string settings and restarting (actually stopping and starting because there was no Restart button) the web job resulted in the certificate for my site being renewed immediately. (It would've expired in 4 days.) Thank you so much!
> 
> While this may work to renew certificates creating new ones still doesn't work.
> 
> I'd also like to know (and this should be specified in the documentation) if the ConnectionStrings are set as appsettings or as connectionstrings.

Doesn't matter. I've done it both ways.

**Comment by DylanTusler** [comment] 2019-10-10 03:51
> Firstly, thanks @sjkp this really is a great extension!
> 
> I'm having the same issue as above when creating a new certificate and tried the above, however my web job is stuck in "Pending Restart" with the error below:
> 
> Any ideas anyone? Thanks in advance!
> 
> > The configuration is not properly set for the Microsoft Azure WebJobs Dashboard. A connection string named AzureWebJobsDashboard is not well-formed.
> > In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.
> > Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.

I had that problem too. I found if you copy the connection string from the storage object itself as I detailed above, that resolved this issue.

**Comment by sjkp** [comment] 2019-10-10 05:25
Hi friends (as hanselman would have said it) 
Microsoft have a work around. We need to browse the KUDU/SCM site using basic auth not SSO. 

Basic Auth is available using https://<yoursite>.scm.azurewebsites.net/basicauth the username + password you need to use are those from the publishing crendential file `userName` and `userPWD`

**Comment by bcornett** [comment] 2019-10-10 05:40
Basic auth worked great for me, thanks for the work around!

**Comment by shanselman** [comment] 2019-10-10 05:45
Just to make it SUPER clear if someone shows up here, @sjkp, the steps (until this is fixed) to force a refresh are:

* Visit https://YOURSITE.scm.azurewebsites.net/basicauth
    * Auth with the dialog, using your FTP/deployment user and pass
* Visit https://YOURSITE.scm.azurewebsites.net/letsencrypt/home/install

**Comment by bclevering** [comment] 2019-10-10 06:44
> Hi friends (as hanselman would have said it)
> Microsoft have a work around. We need to browse the KUDU/SCM site using basic auth not SSO.
> 
> Basic Auth is available using `https://<yoursite>.scm.azurewebsites.net/basicauth` the username + password you need to use are those from the publishing crendential file `userName` and `userPWD`

--
when i try this i get the following error while requesting the certificate:




![image](https://user-images.githubusercontent.com/8439274/66545048-1dacb880-eb3a-11e9-906d-a344d885787e.png)

**Comment by lhuswe** [comment] 2019-10-10 07:05
Basic auth worked great!

**Comment by CaptLunk** [comment] 2019-10-10 07:14
Basic auth works for new .NET core sites as well 👍 Just installed a fresh new cert on a site. 
Thx for all hard work, and a great extension!

**Comment by Variel** [comment] 2019-10-10 07:33
Basic auth works very well! thanks 👍

**Comment by sanderdam** [comment] 2019-10-10 07:47
Fresh new user of the webjob here. The workaround by using basicauth to login to kudu, scm worked like a charm!

**Comment by stephanjohnson** [comment] 2019-10-10 07:51
The workaround of using basicauth worked for me as well.

Thanks for everyone working on this.

@sjkp you're awesome

**Comment by garethrampton** [comment] 2019-10-10 08:28
> > Hi friends (as hanselman would have said it)
> > Microsoft have a work around. We need to browse the KUDU/SCM site using basic auth not SSO.
> > Basic Auth is available using `https://<yoursite>.scm.azurewebsites.net/basicauth` the username + password you need to use are those from the publishing crendential file `userName` and `userPWD`
> 
> --
> when i try this i get the following error while requesting the certificate:
> 
> ![image](https://user-images.githubusercontent.com/8439274/66545048-1dacb880-eb3a-11e9-906d-a344d885787e.png)

Seeing exactly this issue here too

**Comment by webmatikbg** [comment] 2019-10-10 08:31
The workaround of using basicauth worked for me as well.

Thanks

**Comment by sjkp** [comment] 2019-10-10 08:35
@garethrampton @bclevering do you have an app setting configured with letsencrypt:AcmeBaseUri that points to one of the old endpoints? Please use https://acme-v02.api.letsencrypt.org/directory or https://acme-staging-v02.api.letsencrypt.org/directory  for the new V2 endpoints. I'm not sure my 1.0.1 patch handles if you had these configure before, and just did and upgrade.

**Comment by garethrampton** [comment] 2019-10-10 08:50
@sjkp I did have the correct v2 endpoint configure in my app settings, but since removed it - along with the email and hostnames config options too to see if that was impacting things - no change.

Interestingly though - with the same app service plan last night the App Service Acmebot function app was also failing to succeed for the same app, yet this morning it has worked and installed a new certificate.

The app service is in the UK South region, and was newly spun up, so had no pre-existing SSL installed if that makes a difference.

At least now I've got the SSL installed the extension will hopefully now continue to renew with the WebJob.

**Comment by river-robm** [comment] 2019-10-10 09:06
I've used the baiscauth workaround but even after a "Certificate successfully installed" the cert is not applying.

Getting the following webjob error;
Application: LetsEncrypt.SiteExtension.WebJob.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken]](System.Net.HttpStatusCode, System.Net.HttpStatusCode, Boolean, Microsoft.WindowsAzure.Storage.Core.Executor.StorageCommandBase1<Boolean>, System.Exception) at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<ExistsImpl>b__1b(Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand1, System.Net.HttpWebResponse, System.Exception, Microsoft.WindowsAzure.Storage.OperationContext)
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken]

Exception Info: Microsoft.WindowsAzure.Storage.StorageException
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken]
at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.EndExists(System.IAsyncResult)
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass2`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken]].b__0(System.IAsyncResult)
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator+d__1.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageCredentialsValidator+d__0.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider+d__24.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions+d__1.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.JobHost+d__44.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.JobHost+d__25.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Azure.WebJobs.JobHost.Start()
at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
at LetsEncrypt.SiteExtension.WebJob.Program.Main()

I've checked storage configuration and its fine.

**Comment by bclevering** [comment] 2019-10-10 09:19
> @garethrampton @bclevering do you have an app setting configured with letsencrypt:AcmeBaseUri that points to one of the old endpoints? Please use https://acme-v02.api.letsencrypt.org/directory or https://acme-staging-v02.api.letsencrypt.org/directory for the new V2 endpoints. I'm not sure my 1.0.1 patch handles if you had these configure before, and just did and upgrade.

I did update the appsettings in Azure and also did a manual reset of the web app. But still the same issue appears. :(

**Comment by dlucre** [comment] 2019-10-10 10:19
Using BasicAuth also worked for me.  
If you keep getting prompted for the user/pass when trying basic auth, it might be because you're providing the username in the DOMAIN\$USERNAME format.  If so, use $USERNAME only.

**Comment by Jjarrard** [comment] 2019-10-10 10:25
Possibly a stupid question: I'm just using an app service to host a .net core project, and don't have the options to FTP and never set up a username or password. BasicAuth requires a username and password, is it possible to create a user/pass?, or am I not going to be able to use the work around?

**Comment by osvaldolove** [comment] 2019-10-10 10:26
@Jjarrard try downloading the Publish Profile from the overview tab. Credentials should be in the file.

**Comment by Jjarrard** [comment] 2019-10-10 10:28
@osvaldolove brilliant, thanks!

**Comment by Marcel0024** [comment] 2019-10-10 11:13
Workaround also worked for me!

**Comment by Jabe** [comment] 2019-10-10 11:35
To get the credentials, just open the App Service in the **Azure Portal**, go to **Deployment Center** ...

* (if nothing is set up) choose **FTP** and find the **Dashboard** button at the bottom of the blade
* (if you've set up deployment using Deployment Center before) find the **FTP/Credentials** button at the top of the blade

You can also use the **Resource Explorer** to access the API and navigate to config/publishingcredentials.

**Comment by davidverriere** [comment] 2019-10-10 17:33
Using basicAuth and login with FTP credential withou domain works for me
thanks Scott

**Comment by unencode** [comment] 2019-10-10 20:02
Same here, works with Basic. Thanks for the workaround!

**Comment by jjghali** [comment] 2019-10-10 20:08
@shanselman  you are a lifesaver :dancer:

**Comment by valentim89** [comment] 2019-10-11 11:18
Hi Guys,

I am having the same trouble.
When I am attempting the "basicauth" workaround after entering my credentials I get "error 403 - This web app is stopped" 

But it is not!
Can you guys advise?

Thanks for all the effort

**Comment by perkarlssonpayex** [comment] 2019-10-11 11:40
I'm the one who posted the question on Serverfault as mentioned by @tdoumas. 

Changed to basicauth which got me a little bit further, but now I'm stuck with the exact same problem as @bclevering:
![image](https://user-images.githubusercontent.com/39625326/66648198-3779f880-ec2b-11e9-8233-c5a62bc2da53.png)

Also added the letsencrypt:AcmeBaseUri application setting, but it did not make any difference. 

Thankful for help!

**Comment by seriousfish** [comment] 2019-10-11 19:06
Basic Auth also worked for me, but the Webjob never gets created? Any instructions to create that manually with the settings I need?

**Comment by ahmelsayed** [comment] 2019-10-11 19:17
Quick update from Azure side; a fix started rolling out yesterday, we're tracking updating some US regions today and finishing the upgrade globally by next week.

**Comment by sjkp** [comment] 2019-10-13 21:16
Please update to 1.0.4 to get proper error reporting. And then make a new issues, unless it is related to this one, if you still have errors.

**Closed by sjkp** 2019-10-13 21:16 UTC
Labels: bug

**Comment by robertmclaws** [comment] 2019-10-14 00:15
I'm still getting the same error with 1.0.4, even after totally uninstalling and reinstalling the extension. The only luck I had was with the /basicauth workaround. I have a couple other sites to set up, but I'll hold off for a couple days till the rest of the rollout happens.

**Comment by m4nthys** [comment] 2019-10-14 01:42
> Please update to 1.0.4 to get proper error reporting. And then make new issues, unless it is related to this one, if you still have errors.

I still have the same error with 1.1.4. =/

**Comment by sjkp** [comment] 2019-10-14 06:44
1.0.4 doesn't fix the 502 problem that Microsoft introduced, you still have to use basic auth, until their fix is rolled out. I can't fix the app service infrastructure ;)

**Comment by alfkla** [comment] 2019-10-14 11:20
Hi, thanks for wonderfull extension, I use it a lot! I have updated it to 1.0.4 on one webapp today and tried to run it, but it still fails. Then I tried the login at https://<yoursite>.scm.azurewebsites.net/basicauth (with credentials from the publish profile) and got into the Kudu environment page. But what's next, if I try to continue using https://<yoursite>.scm.azurewebsites.net/letsencrypt/home/install (writing this url in the address field in my webbrowser) I only end up with this error:

Server Error in '/letsencrypt' Application.
'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)
Parameter name: authority
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

![smsapi_error](https://user-images.githubusercontent.com/17759364/66747642-51167c80-ee85-11e9-8b44-f0f0f74dddbe.png)


Any ideas of what I am doing wrong?

Kind regards, Alf

**Comment by shanselman** [comment] 2019-10-14 17:57
I'm told the fix is being rolled out ASAP.

**Comment by RobDeVoer** [comment] 2019-10-14 22:50
Big thanks @sjkp and @shanselman for your efforts to get this resolved. Really appreciated.

**Comment by sjkp** [comment] 2019-10-15 07:59
@alfkla please start at ` https://<your-site>.scm.azurewebsites.net/letsencrypt/` unless you have already configured the site before. 
And use basicauth as you did, until we have a confirmation that the patch is applied globally.

**Comment by Marcel0024** [comment] 2019-10-15 10:22
Still getting 502 in west Europe

**Comment by shanselman** [comment] 2019-10-16 18:12
This should be patched everywhere now.

**Comment by kilasuit** [comment] 2019-10-17 00:27
> This should be patched everywhere now.

I can confirm this now looks to be working as expected as I have managed to get a new Certificate where I was unable to previously

**Comment by alfkla** [comment] 2019-10-17 11:03
Thanks a lot @sjkp and @shanselman - now it works fine!

**Comment by Petryxasport** [comment] 2019-10-21 13:54
@sjkp thanks, now everything works correctly!

**Comment by akanshayadav11** [comment] 2020-05-08 11:21
Great article! Thanks!

I want to do a comment if you allow me.

https://dipoletechi.com/blog-post/502-web-server-received-an-invalid-response-while-acting-as-a-gateway-or-proxy-server-on-azure-web-app/

**Comment by asp1egui** [comment] 2020-05-09 16:23
> Great article! Thanks!
> 
> I want to do a comment if you allow me.
> 
> https://dipoletechi.com/blog-post/502-web-server-received-an-invalid-response-while-acting-as-a-gateway-or-proxy-server-on-azure-web-app/

so the only option is to upgrade the service plan ?

**Comment by akanshayadav11** [comment] 2020-05-09 17:18
This may be vary for different scenario


Sent from Outlook Mobile


From: asp1egui <notifications@github.com>Sent: Saturday, May 9, 2020, 9:53 PMTo: sjkp/letsencrypt-siteextensionCc: akanshayadav11; CommentSubject: Re: [sjkp/letsencrypt-siteextension] 502 - Web server received an invalid response while acting as a gateway or proxy server. (#331)

Great article! Thanks!
I want to do a comment if you allow me.
https://dipoletechi.com/blog-post/502-web-server-received-an-invalid-response-while-acting-as-a-gateway-or-proxy-server-on-azure-web-app/

so the only option is to upgrade the service plan ?
